### ISSUE TITLE
Update Readme File

### ISSUE THREAD

**Issue by thevaibhavmaurya** [vaibhav-xt/Vanilla-Javascript-Projects#2]
Write about the Vanilla Javascript project. How does it goings to help beginners? 
Don't remove previous data.

**Comment by Yvg2244** [comment]
@vaibhav-xt could you please assign it to me

**Comment by YohanesGetinet1** [comment]
Sir could you assign this task to me

**Comment by thevaibhavmaurya** [comment]
Thanks for contribution
